import {assert} from '@augment-vir/assert';
import {
    camelCaseToKebabCase,
    collapseWhiteSpace,
    log,
    wrapString,
    type PartialWithUndefined,
    type RequiredAndNotNull,
} from '@augment-vir/common';
import {interpolationSafeWindowsPath, runShellCommand} from '@augment-vir/node';
import {getNowInUtcTimezone} from 'date-vir';
import {existsSync} from 'node:fs';
import {mkdir, readdir, readFile, writeFile} from 'node:fs/promises';
import {dirname, join} from 'node:path';
import {getDefaultSchemaPath} from '../util/default-paths.js';

/**
 * Params for {@link createPgliteMigration}
 *
 * @category Internal
 */
export type PgliteMigrationParams = PartialWithUndefined<{
    /**
     * Path to the Prisma generated `migrations` folder. If this is not provided, it will be deduced
     * from the provided or defaulted `schemaFilePath`.
     */
    migrationsDirPath: string;
    /**
     * Path to your Prisma schema file. If this is not provided, it will be deduced from the
     * provided `migrationsDirPath` or your cwd.
     *
     * @default
     * migrationsDirPath ? join(dirname(migrationsDirPath), 'schema.prisma') : join(process.cwd(), 'prisma', 'schema.prisma')
     */
    schemaFilePath: string;
    /**
     * The file name for snapshots saved into the migrations folder. This defaults to a name that
     * won't easily clash with the actual `schema.prisma` file when devs are searching for it.
     *
     * @default 'source.snapshot'
     */
    snapshotFileName: string;
    /**
     * Enable logging.
     *
     * @default false
     */
    enableLogs: boolean;
}> & {
    /** The name of the new migration, if one is needed. */
    migrationName: string;
};

type ResolvedPgliteMigrationParams = RequiredAndNotNull<PgliteMigrationParams>;

/**
 * Default file name for a migration schema snapshot.
 *
 * @category Internal
 */
export const defaultSnapshotFileName = 'source.snapshot';

function finalizeMigrationParams(
    params: Readonly<PgliteMigrationParams>,
): ResolvedPgliteMigrationParams {
    const schemaFilePath: string =
        params.schemaFilePath ||
        (params.migrationsDirPath
            ? join(dirname(params.migrationsDirPath), 'schema.prisma')
            : getDefaultSchemaPath());
    const migrationsDirPath: string =
        params.migrationsDirPath || join(dirname(schemaFilePath), 'migrations');

    assert.isTruthy(migrationsDirPath, 'Unable to determine migrationsDirPath.');
    assert.isTruthy(schemaFilePath, 'Unable to determine schemaFilePath.');
    assert.isTrue(
        existsSync(schemaFilePath),
        `schemaFilePath does not exist: '${schemaFilePath}'.`,
    );

    const snapshotFileName = params.snapshotFileName || defaultSnapshotFileName;

    return {
        migrationsDirPath,
        schemaFilePath,
        enableLogs: !!params.enableLogs,
        snapshotFileName,
        migrationName: sanitizeMigrationName(params.migrationName),
    };
}

/**
 * Output from {@link createPgliteMigration}.
 *
 * @category Internal
 */
export type PgliteMigration = {
    migrationName: string;
    migrationDirPath: string;
};

/**
 * Migration lock file name required by Prisma to deploy migrations.
 *
 * @category Internal
 */
export const migrationLockFileName = 'migration_lock.toml';
/**
 * Contents of the migration lock file as required by this plugin (specifically, using postgres).
 *
 * @category Internal
 */
export const migrationLockFileContents = [
    '# Please do not edit this file manually',
    '# It should be added in your version-control system (e.g., Git)',
    'provider = "postgresql"',
].join('\n');

/**
 * Create a dev migration using Prisma with a PGlite database. This is analogous to running `prisma
 * migrate dev` with a plain Postgres database.
 *
 * @category CLI
 * @returns {@link PgliteMigration} If the migration was created, otherwise `undefined`.
 */
export async function createPgliteMigration(
    params: Readonly<PgliteMigrationParams>,
): Promise<PgliteMigration | undefined> {
    const {migrationsDirPath, schemaFilePath, enableLogs, snapshotFileName, migrationName} =
        finalizeMigrationParams(params);

    const now = getNowInUtcTimezone();

    const migrationTime = [
        now.year,
        now.month,
        now.day,
        now.hour,
        now.minute,
        now.second,
    ]
        .map((entry) => String(entry).padStart(2, '0'))
        .join('');

    const previousSchema = await findLatestMigrationPath(migrationsDirPath);
    const fromArgs = previousSchema
        ? [
              '--from-schema-datamodel',
              wrapString({
                  value: interpolationSafeWindowsPath(join(previousSchema, snapshotFileName)),
                  wrapper: "'",
              }),
          ]
        : ['--from-empty'];

    const diffCommand = [
        'prisma',
        'migrate',
        'diff',
        ...fromArgs,
        '--to-schema-datamodel',
        wrapString({value: interpolationSafeWindowsPath(schemaFilePath), wrapper: "'"}),
        '--script',
        '--exit-code',
    ].join(' ');

    log.if(enableLogs).faint(
        [
            '>',
            diffCommand,
            '\n',
        ].join(' '),
    );

    const output = await runShellCommand(diffCommand, {
        hookUpToConsole: false,
        rejectOnError: false,
    });

    if (output.exitCode === 0) {
        log.warning('No changes detected.');
        return undefined;
        /* node:coverage ignore next 3: idk how to trigger this intentionally */
    } else if (output.exitCode === 1) {
        throw new Error(output.stderr);
    }

    const migrationDirName = [
        migrationTime,
        migrationName,
    ].join('_');

    const newMigrationDirPath = join(migrationsDirPath, migrationDirName);

    await mkdir(newMigrationDirPath, {recursive: true});
    const migrationOutputPath = join(newMigrationDirPath, 'migration.sql');
    await writeFile(migrationOutputPath, output.stdout);
    await writeFile(
        join(newMigrationDirPath, snapshotFileName),
        [
            '// Please do not edit this file manually.',
            '// This file is required for keeping track of migration progress for PGlite databases.',
            '// This file should be added in your version-control system (e.g., Git).',
            '// Only the most recent snapshot must be kept, all previous snapshots can be deleted.',
            '\n',
            String(await readFile(schemaFilePath)),
        ].join('\n'),
    );
    const migrationLockFilePath = join(migrationsDirPath, migrationLockFileName);
    if (!existsSync(migrationLockFilePath)) {
        await writeFile(migrationLockFilePath, migrationLockFileContents);
    }

    log.success(`Migration created: ${migrationDirName}`);

    return {
        migrationDirPath: newMigrationDirPath,
        migrationName: migrationDirName,
    };
}

/**
 * Sanitize a user provided migration name so it fits Prisma's naming scheme conventions /
 * requirements.
 *
 * @category Internal
 */
export function sanitizeMigrationName(originalName: string): string {
    return camelCaseToKebabCase(collapseWhiteSpace(originalName).replaceAll(' ', '-'))
        .replaceAll('-', '_')
        .toLowerCase();
}

/**
 * Finds the latest Prisma migration folder within the given migrations folder.
 *
 * @category Internal
 */
export async function findLatestMigrationPath(
    migrationsDirPath: string,
): Promise<string | undefined> {
    if (!existsSync(migrationsDirPath)) {
        return undefined;
    }

    const migrationDirs = (await readdir(migrationsDirPath, {withFileTypes: true})).filter(
        (entry) => entry.isDirectory(),
    );

    const latestMigrationDir = migrationDirs.toSorted((a, b) => b.name.localeCompare(a.name))[0];

    if (!latestMigrationDir) {
        return undefined;
    }

    return join(migrationsDirPath, latestMigrationDir.name);
}
